# Generated by Django 5.0.7 on 2025-04-29 01:59

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Meeting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="موضوع")),
                (
                    "date",
                    django_jalali.db.models.jDateField(
                        blank=True, null=True, verbose_name="تاریخ"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="شرح")),
                (
                    "participants",
                    models.ManyToManyField(
                        related_name="meetings", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "start_date",
                    django_jalali.db.models.jDateField(
                        blank=True, null=True, verbose_name="تاریخ شروع"
                    ),
                ),
                (
                    "end_date",
                    django_jalali.db.models.jDateField(
                        blank=True, null=True, verbose_name="تاریخ پایان"
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        related_name="projects", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="موضوع"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="شرح"),
                ),
                (
                    "due_date",
                    django_jalali.db.models.jDateField(
                        blank=True, null=True, verbose_name="تاریخ"
                    ),
                ),
                ("is_completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        help_text="کاربری که این تسک به او محول شده",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assigned_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="کاربری که این تسک را ایجاد کرده",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        blank=True,
                        help_text="اگر این تسک در یک جلسه ایجاد شده باشد، اینجا ثبت می\u200cشود",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="meeting_tasks",
                        to="taskflow.meeting",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        help_text="پروژه\u200cای که این تسک به آن تعلق دارد",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="taskflow.project",
                    ),
                ),
            ],
        ),
    ]
