# Generated by Django 5.0.7 on 2025-04-29 02:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="نام"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="نام خانوادگی",
                    ),
                ),
                (
                    "mellicode",
                    models.CharField(max_length=10, unique=True, verbose_name="کد ملی"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=11, null=True, verbose_name="شماره ثابت"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, max_length=11, null=True, verbose_name="تلفن همراه"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="شهر"
                    ),
                ),
                (
                    "code_posti",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="کدپستی"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="آدرس"
                    ),
                ),
                (
                    "total_loan_amount",
                    models.BigIntegerField(
                        default=0, verbose_name="مجموع وام\u200cهای دریافتی"
                    ),
                ),
                (
                    "total_loan_balance",
                    models.BigIntegerField(
                        default=0, verbose_name="مانده کل وام\u200cها"
                    ),
                ),
                (
                    "total_repaid",
                    models.BigIntegerField(
                        default=0, verbose_name="مجموع پرداختی مشتری"
                    ),
                ),
            ],
            options={
                "verbose_name": "مشتری",
                "verbose_name_plural": "مشتریان",
            },
        ),
        migrations.CreateModel(
            name="HomeImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="home_images/")),
                ("description", models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Seller",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="نام"
                    ),
                ),
                (
                    "seller_porsant",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="پورسانت فروشنده",
                    ),
                ),
            ],
            options={
                "verbose_name": "فروشنده",
                "verbose_name_plural": "فروشندگان",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "f_name",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="نام"
                    ),
                ),
                (
                    "l_name",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="فامیلی"
                    ),
                ),
                (
                    "mellicod",
                    models.CharField(max_length=10, unique=True, verbose_name="کدملی"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=11, null=True, verbose_name="موبایل"
                    ),
                ),
                (
                    "create",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="تاریخ"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("EMPLOYEE", "Employee"),
                            ("MANAGER", "Manager"),
                            ("CEO", "CEO"),
                        ],
                        default="EMPLOYEE",
                        max_length=10,
                        verbose_name="نقش",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_admin", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        help_text="مدیری که این کاربر زیرمجموعه\u200cی اوست",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="team_members",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="مدیریت",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "کاربر",
                "verbose_name_plural": "کاربران",
            },
        ),
    ]
