# Generated by Django 5.0.7 on 2025-04-29 03:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="permission",
            field=models.ManyToManyField(related_name="users", to="auth.permission"),
        ),
    ]
