# Generated by Django 5.0.7 on 2025-04-29 02:53

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("", ""),
                            ("آزاد", "آزاد"),
                            ("بتا", "بتا"),
                            ("سازمانی", "سازمانی"),
                            ("نمایندگی", "نمایندگی"),
                        ],
                        default="none",
                        max_length=10,
                        verbose_name="طرح وام",
                    ),
                ),
                (
                    "loan_code",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="کد وام"
                    ),
                ),
                ("total_amount", models.BigIntegerField(verbose_name="مبلغ اصل وام")),
                (
                    "final_amount",
                    models.BigIntegerField(verbose_name="بازپرداخت نهایی"),
                ),
                (
                    "loan_date",
                    django_jalali.db.models.jDateField(
                        blank=True, null=True, verbose_name="تاریخ اخذ وام"
                    ),
                ),
                (
                    "start_date",
                    django_jalali.db.models.jDateField(
                        blank=True, null=True, verbose_name="تاریخ اولین قسط"
                    ),
                ),
                (
                    "end_date",
                    django_jalali.db.models.jDateField(
                        blank=True, null=True, verbose_name="تاریخ آخرین قسط"
                    ),
                ),
                (
                    "num_month",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="مدت وام(ماه)"
                    ),
                ),
                (
                    "num_installments",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="تعداد بازپرداخت"
                    ),
                ),
                (
                    "total_received_customer",
                    models.BigIntegerField(default=0, verbose_name="جمع پرداختی مشتری"),
                ),
                (
                    "loan_mande_bedehi",
                    models.BigIntegerField(default=0, verbose_name="مانده بدهی وام"),
                ),
                ("installments_created", models.BooleanField(default=False)),
                (
                    "tasviye_status",
                    models.BooleanField(default=False, verbose_name="وضعیت تسویه"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loans",
                        to="accounts.customer",
                        verbose_name="مشتری",
                    ),
                ),
            ],
            options={
                "verbose_name": "وام",
                "verbose_name_plural": "وامها",
            },
        ),
        migrations.CreateModel(
            name="Installment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ghest_count",
                    models.PositiveIntegerField(default=0, verbose_name="شماره قسط"),
                ),
                (
                    "amount",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="مبلغ قسط"
                    ),
                ),
                (
                    "due_date",
                    django_jalali.db.models.jDateField(
                        blank=True, null=True, verbose_name="تاریخ سررسید"
                    ),
                ),
                (
                    "paid",
                    models.BooleanField(default=False, verbose_name="وضعیت پرداخت"),
                ),
                (
                    "ghest_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("نقدی", "نقدی"),
                            ("بتا", "بتا"),
                            ("چک", "چک"),
                            ("نمایندگی", "نمایندگی"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="نوع قسط",
                    ),
                ),
                (
                    "ghest_place",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="محل وصول قسط",
                    ),
                ),
                (
                    "total_ghest_repaid",
                    models.PositiveIntegerField(
                        default=0, verbose_name="جمع بازپرداخت\u200c هر قسط"
                    ),
                ),
                (
                    "penalty_amount",
                    models.PositiveIntegerField(
                        default=0, verbose_name="دیرکرد هر قسط"
                    ),
                ),
                (
                    "created_at",
                    django_jalali.db.models.jDateTimeField(auto_now_add=True),
                ),
                ("updated_at", django_jalali.db.models.jDateTimeField(auto_now=True)),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="installments",
                        to="demand.loan",
                        verbose_name="مشتری",
                    ),
                ),
            ],
            options={
                "verbose_name": "مطالبات",
                "verbose_name_plural": "مطالبات",
            },
        ),
        migrations.CreateModel(
            name="Guarantee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guarantor_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="نام ضامن"
                    ),
                ),
                (
                    "guarantee_amount",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="مبلغ ضمانت"
                    ),
                ),
                (
                    "guarantee_serial",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="سریال تضامین",
                    ),
                ),
                (
                    "guarantee_type",
                    models.CharField(
                        blank=True,
                        choices=[("check", "چک"), ("safte", "سفته")],
                        max_length=20,
                        null=True,
                        verbose_name="نوع ضمانت",
                    ),
                ),
                (
                    "guarantee_date",
                    django_jalali.db.models.jDateField(
                        blank=True, null=True, verbose_name="تاریخ ضمانت"
                    ),
                ),
                (
                    "guarantor_address",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="آدرس ضامن"
                    ),
                ),
                (
                    "guarantor_phone",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        verbose_name="شماره تماس ضامن",
                    ),
                ),
                (
                    "guarantor_mellicod",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="کد ملی ضامن"
                    ),
                ),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guarantees",
                        to="demand.loan",
                        verbose_name="وام",
                    ),
                ),
            ],
            options={
                "verbose_name": "ضامن",
                "verbose_name_plural": "ضمانت",
            },
        ),
        migrations.CreateModel(
            name="LoanSettlement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "settlement_date",
                    django_jalali.db.models.jDateField(
                        blank=True, null=True, verbose_name="تاریخ تسویه"
                    ),
                ),
                (
                    "settled_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="مبلغ تسویه",
                    ),
                ),
                (
                    "settlement_method",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="روش تسویه"
                    ),
                ),
                (
                    "penalty_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="مبلغ جریمه",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="شرح تسویه"),
                ),
                (
                    "return_garanti",
                    models.BooleanField(
                        default=False, verbose_name="وضعیت برگشت تضامین"
                    ),
                ),
                (
                    "return_date",
                    django_jalali.db.models.jDateField(
                        blank=True, null=True, verbose_name="تاریخ بازگشت تضامین"
                    ),
                ),
                (
                    "settlement_status",
                    models.BooleanField(default=False, verbose_name="وضعیت تسویه"),
                ),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settlements",
                        to="demand.loan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Repayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "repayment_amount",
                    models.PositiveIntegerField(verbose_name="بازپرداخت قسط"),
                ),
                (
                    "repayment_date",
                    django_jalali.db.models.jDateField(
                        blank=True, null=True, verbose_name="تاریخ بازپرداخت"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("cash", "واریز به حساب"),
                            ("chek", "چک"),
                            ("link", "لینک"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="نحوه پرداخت",
                    ),
                ),
                (
                    "payment_voucher",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="رسید پرداخت",
                    ),
                ),
                (
                    "payment_place",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("رفاه", "رفاه "),
                            ("سپه", "سپه "),
                            ("ملت", "ملت "),
                            ("پست بانک", "پست بانک"),
                            ("صادرات", "صادرات"),
                            ("تجارت", "تجارت"),
                            ("سایر", "سایر"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="محل  پرداخت",
                    ),
                ),
                (
                    "created_at",
                    django_jalali.db.models.jDateTimeField(auto_now_add=True),
                ),
                (
                    "installment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repayments",
                        to="demand.installment",
                    ),
                ),
            ],
            options={
                "verbose_name": "پرداخت",
                "verbose_name_plural": "پرداختها",
            },
        ),
    ]
