# Generated by Django 5.0.7 on 2025-05-11 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("demand", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="guarantee",
            name="guarantor_phone2",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="شماره تماس 2"
            ),
        ),
        migrations.AddField(
            model_name="guarantee",
            name="guarantor_phone3",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="شماره تماس ثابت"
            ),
        ),
    ]
