# Generated by Django 5.0.7 on 2025-05-11 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("demand", "0002_guarantee_guarantor_phone2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="guarantee",
            name="guarantor_address2",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="آدرس محل کار"
            ),
        ),
    ]
