# Generated by Django 5.0.7 on 2025-04-29 02:53

import django.db.models.deletion
import django.utils.timezone
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DigiInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    django_jalali.db.models.jDateField(
                        blank=True, null=True, verbose_name="تاریخ فاکتور"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("paid", "پرداخت شده"),
                            ("unfinish", "ناتمام"),
                            ("cancle", "لغو"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="وضعیت فاکتور",
                    ),
                ),
                (
                    "total_digiprice",
                    models.BigIntegerField(
                        default=0, editable=False, verbose_name="مبلغ کل فاکتور"
                    ),
                ),
                (
                    "total_digipaid",
                    models.BigIntegerField(
                        default=0, verbose_name="جمع پرداخت\u200cهای مشتری"
                    ),
                ),
                (
                    "total_digidiscount",
                    models.BigIntegerField(default=0, verbose_name="تخفیف فاکتور"),
                ),
                (
                    "total_digiremain_amount",
                    models.BigIntegerField(
                        default=0, verbose_name="جمع مبلغ مانده مشتری"
                    ),
                ),
                (
                    "created_at",
                    django_jalali.db.models.jDateTimeField(
                        default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", django_jalali.db.models.jDateTimeField(auto_now=True)),
                (
                    "customersale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="digiinvoices",
                        to="accounts.customer",
                        verbose_name="مشتری",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="digiinvoices",
                        to="accounts.seller",
                        verbose_name="فروشنده",
                    ),
                ),
            ],
            options={
                "verbose_name": "فاکتور دیجیتال",
                "verbose_name_plural": "فاکتورهای دیجیتال",
            },
        ),
        migrations.CreateModel(
            name="DigiPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("digiamount", models.PositiveIntegerField(verbose_name="مبلغ پرداخت")),
                (
                    "digidiscount",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="تخفیف "
                    ),
                ),
                (
                    "discount_code",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="کد تخفیف"
                    ),
                ),
                (
                    "etebar",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="مبلغ اعتبار "
                    ),
                ),
                (
                    "etebar_code",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="کد اعتبار"
                    ),
                ),
                (
                    "pay_date",
                    django_jalali.db.models.jDateField(
                        blank=True, null=True, verbose_name="تاریخ پرداخت"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("نقدی", "نقدی"),
                            ("اعتباری", "اعتباری"),
                            ("تهاتر", "تهاتر"),
                        ],
                        max_length=50,
                        verbose_name="روش پرداخت",
                    ),
                ),
                (
                    "payment_explain",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="شرح پرداخت"
                    ),
                ),
                (
                    "digipayment_receipt",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="رسید پرداخت"
                    ),
                ),
                (
                    "digipayment_confirm",
                    models.BooleanField(default=False, verbose_name="تایید پرداخت"),
                ),
                (
                    "digiinvoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="digipayments",
                        to="sale.digiinvoice",
                        verbose_name="فاکتور دیجیتال",
                    ),
                ),
            ],
            options={
                "verbose_name": "پرداخت دیجیتال",
                "verbose_name_plural": "پرداختهای دیجیتال",
            },
        ),
        migrations.CreateModel(
            name="DigiProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "digicode",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="کد کالا"
                    ),
                ),
                (
                    "diginame",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="نام کالا"
                    ),
                ),
                (
                    "qty",
                    models.IntegerField(blank=True, null=True, verbose_name="تعداد"),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="رنگ کالا"
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="برند کالا"
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="مدل"
                    ),
                ),
                (
                    "sale_tax",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="مالیات فروش"
                    ),
                ),
                (
                    "unit_price",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="قیمت واحد"
                    ),
                ),
                (
                    "digiprice",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="قیمت فروش کالا"
                    ),
                ),
                (
                    "porsant_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="پورسانت",
                    ),
                ),
                (
                    "digiinvoice",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="digiitems",
                        to="sale.digiinvoice",
                        verbose_name="فاکتور",
                    ),
                ),
            ],
            options={
                "verbose_name": "محصول دیجیتال",
                "verbose_name_plural": "محصولات دیجیتال",
            },
        ),
        migrations.CreateModel(
            name="GoldInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    django_jalali.db.models.jDateField(
                        blank=True, null=True, verbose_name="تاریخ فاکتور"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("paid", "پرداخت شده"),
                            ("unfinish", "ناتمام"),
                            ("cancle", "لغو"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="وضعیت فاکتور",
                    ),
                ),
                (
                    "total_amount",
                    models.BigIntegerField(
                        default=0, editable=False, verbose_name="مبلغ کل فاکتور"
                    ),
                ),
                (
                    "total_paid",
                    models.BigIntegerField(
                        default=0, verbose_name="جمع پرداخت\u200cهای مشتری"
                    ),
                ),
                (
                    "total_weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="جمع وزن فاکتور",
                    ),
                ),
                (
                    "total_discount",
                    models.BigIntegerField(default=0, verbose_name="تخفیف فاکتور"),
                ),
                (
                    "total_calcu_amount",
                    models.BigIntegerField(default=0, verbose_name="جمع مبلغ محاسبه"),
                ),
                (
                    "total_remain_amount",
                    models.BigIntegerField(
                        default=0, verbose_name="جمع مبلغ مانده مشتری"
                    ),
                ),
                (
                    "created_at",
                    django_jalali.db.models.jDateTimeField(
                        default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", django_jalali.db.models.jDateTimeField(auto_now=True)),
                (
                    "customersale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goldinvoices",
                        to="accounts.customer",
                        verbose_name="مشتری",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goldinvoices",
                        to="accounts.seller",
                        verbose_name="فروشنده",
                    ),
                ),
            ],
            options={
                "verbose_name": "فاکتور طلا",
                "verbose_name_plural": "فاکتورهای طلا",
            },
        ),
        migrations.CreateModel(
            name="GoldPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.PositiveIntegerField(verbose_name="مبلغ پرداخت")),
                (
                    "discount",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="تخفیف "
                    ),
                ),
                (
                    "discount_code",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="کد تخفیف"
                    ),
                ),
                (
                    "etebar",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="اعتبار "
                    ),
                ),
                (
                    "etebar_code",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="کد اعتبار"
                    ),
                ),
                (
                    "pay_date",
                    django_jalali.db.models.jDateField(
                        blank=True, null=True, verbose_name="تاریخ پرداخت"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("نقدی", "نقدی"),
                            ("اعتباری", "اعتباری"),
                            ("تهاتر", "تهاتر"),
                        ],
                        max_length=50,
                        verbose_name="روش پرداخت",
                    ),
                ),
                (
                    "payment_explain",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="شرح پرداخت"
                    ),
                ),
                (
                    "payment_receipt",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="رسید پرداخت"
                    ),
                ),
                (
                    "payment_confirm",
                    models.BooleanField(default=False, verbose_name="تایید پرداخت"),
                ),
                (
                    "goldinvoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="sale.goldinvoice",
                        verbose_name="فاکتور طلا",
                    ),
                ),
            ],
            options={
                "verbose_name": "پرداخت طلا",
                "verbose_name_plural": "پرداختهای طلا",
            },
        ),
        migrations.CreateModel(
            name="GoldProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "goldcode",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="کد کالا",
                    ),
                ),
                (
                    "goldname",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="نام کالا"
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="وزن"
                    ),
                ),
                (
                    "karat",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="عیار"
                    ),
                ),
                (
                    "sale_ojrat",
                    models.DecimalField(
                        decimal_places=1, max_digits=15, verbose_name="اجرت فروش"
                    ),
                ),
                (
                    "buy_ojrat",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=15,
                        null=True,
                        verbose_name="اجرت خرید",
                    ),
                ),
                (
                    "seller_benefit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=15,
                        null=True,
                        verbose_name="سود فروشنده",
                    ),
                ),
                (
                    "sele_benefit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=15,
                        null=True,
                        verbose_name="سود وزنی فروش",
                    ),
                ),
                ("sale_tax", models.BigIntegerField(verbose_name="مالیات فروش")),
                ("daily_price", models.BigIntegerField(verbose_name="قیمت روز طلا")),
                ("price", models.BigIntegerField(verbose_name="قیمت فروش کالا")),
                (
                    "calcu_amount",
                    models.BigIntegerField(default=0, verbose_name=" مبلغ محاسبه"),
                ),
                (
                    "porsant_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="پورسانت",
                    ),
                ),
                (
                    "goldinvoice",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="golditems",
                        to="sale.goldinvoice",
                        verbose_name="فاکتور",
                    ),
                ),
            ],
            options={
                "verbose_name": "محصول طلا",
                "verbose_name_plural": "محصولات طلا",
            },
        ),
    ]
